# Generated by Django 3.2 on 2021-06-08 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210607_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='drive',
            name='drive_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 14, 45, 7, 571481), verbose_name='Время поездки'),
        ),
    ]
