# Generated by Django 3.2 on 2021-06-08 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210608_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 15, 42, 4, 458441), verbose_name='Время поездки'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='drive_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
