# Generated by Django 3.2 on 2021-06-08 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210608_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 18, 10, 17, 307225), verbose_name='Время поездки'),
        ),
    ]
